import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://docs.hadona.id'

  // Define all routes
  const routes = [
    '',
    // Agency - Onboarding
    '/agency',
    '/agency/onboarding',
    '/agency/onboarding/selamat-datang',
    '/agency/onboarding/mengapa-hadona',
    '/agency/onboarding/proses-onboarding',
    '/agency/onboarding/persiapan',
    '/agency/onboarding/kickoff-meeting',
    // Agency - Business Manager
    '/agency/business-manager',
    '/agency/business-manager/membuat-business-manager',
    '/agency/business-manager/linking-fanspage',
    '/agency/business-manager/menautkan-page',
    '/agency/business-manager/menautkan-instagram',
    '/agency/business-manager/menautkan-ad-account',
    '/agency/business-manager/menambahkan-people-ad-account',
    '/agency/business-manager/permission',
    '/agency/business-manager/2fa',
    '/agency/business-manager/verifikasi',
    '/agency/business-manager/troubleshooting',
    // Agency - User Management
    '/agency/user-management',
    '/agency/user-management/menambahkan-team',
    '/agency/user-management/role-permission',
    '/agency/user-management/mengatur-akses',
    '/agency/user-management/menghapus-user',
    '/agency/user-management/monitoring',
    '/agency/user-management/audit-log',
    // Agency - Ads Setup
    '/agency/ads-setup',
    '/agency/ads-setup/setup-ads-manager',
    '/agency/ads-setup/membuat-campaign',
    '/agency/ads-setup/setup-audience',
    '/agency/ads-setup/mengatur-budget',
    '/agency/ads-setup/instagram-ads',
    '/agency/ads-setup/whatsapp-ads',
    '/agency/ads-setup/instagram-whatsapp-linking',
    '/agency/ads-setup/creative-best-practices',
    '/agency/ads-setup/ab-testing',
    '/agency/ads-setup/optimasi-campaign',
    '/agency/ads-setup/reporting-analytics',
    '/agency/ads-setup/troubleshooting',
    // Agency - Best Practices
    '/agency/best-practices',
    '/agency/best-practices/content-strategy',
    '/agency/best-practices/budget-management',
    '/agency/best-practices/optimasi-performance',
    '/agency/best-practices/keamanan-akun',
    '/agency/best-practices/community',
    '/agency/best-practices/troubleshooting-umum',
    '/agency/best-practices/faq',
    '/agency/best-practices/kontak-support',
    '/agency/best-practices/resources',
    '/agency/best-practices/updates',
    // Whitelist - Onboarding
    '/whitelist',
    '/whitelist/onboarding',
    '/whitelist/onboarding/registrasi-dashboard',
    '/whitelist/onboarding/request-ads-account-meta',
    '/whitelist/onboarding/request-ads-account-google',
    // Whitelist - Pixel Setup
    '/whitelist/pixel-setup',
    '/whitelist/pixel-setup/pengenalan',
    '/whitelist/pixel-setup/membuat-pixel',
    '/whitelist/pixel-setup/instalasi-partner',
    '/whitelist/pixel-setup/instalasi-manual',
    '/whitelist/pixel-setup/verifikasi',
    '/whitelist/pixel-setup/testing',
    '/whitelist/pixel-setup/troubleshooting',
    // Whitelist - UTM Configuration
    '/whitelist/utm-configuration',
    '/whitelist/utm-configuration/pengenalan',
    '/whitelist/utm-configuration/utm-source',
    '/whitelist/utm-configuration/utm-medium',
    '/whitelist/utm-configuration/utm-campaign',
    '/whitelist/utm-configuration/utm-id',
    '/whitelist/utm-configuration/setup-meta-ads',
    // Whitelist - Google Integration
    '/whitelist/google-integration',
    '/whitelist/google-integration/pengenalan-ga4',
    '/whitelist/google-integration/setup-ga4',
    '/whitelist/google-integration/authentication',
    '/whitelist/google-integration/linking-google-ads',
    '/whitelist/google-integration/event-mapping',
    '/whitelist/google-integration/custom-dimensions',
    '/whitelist/google-integration/verifikasi',
    '/whitelist/google-integration/best-practices',
    '/whitelist/google-integration/troubleshooting',
    // Whitelist - Data Sync
    '/whitelist/data-sync',
    '/whitelist/data-sync/import-ga4',
    '/whitelist/data-sync/auto-sync',
    '/whitelist/data-sync/mapping-events',
    '/whitelist/data-sync/data-validation',
    '/whitelist/data-sync/monitoring',
    '/whitelist/data-sync/troubleshooting',
    // Whitelist - Monitoring
    '/whitelist/monitoring',
    '/whitelist/monitoring/events-manager',
    '/whitelist/monitoring/ga4-data',
    '/whitelist/monitoring/interpretasi-metrics',
    '/whitelist/monitoring/custom-reports',
    '/whitelist/monitoring/alerts',
    '/whitelist/monitoring/data-export',
    '/whitelist/monitoring/troubleshooting',
    // Whitelist - Advanced Setup
    '/whitelist/advanced-setup',
    '/whitelist/advanced-setup/conversions-api',
    '/whitelist/advanced-setup/server-side-tracking',
    '/whitelist/advanced-setup/custom-events',
    '/whitelist/advanced-setup/advanced-events',
    '/whitelist/advanced-setup/data-layer',
    '/whitelist/advanced-setup/webhooks',
    '/whitelist/advanced-setup/performance',
    '/whitelist/advanced-setup/privacy-compliance',
  ]

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: route === '' ? 1 : (route === '/agency' || route === '/whitelist') ? 0.9 : route.split('/').length === 3 ? 0.8 : 0.7,
  }))
}